### ISSUE TITLE
Solving environment for python dependencies fails

### ISSUE THREAD

**Issue by walidabualafia** [Xinglab/IRIS#10]
Hello,

I was just trying to install IRIS using the `./install all` command. The three `## Package Plan ##` environments get built, but when `checking python dependencies`, the `solving environment` buffers indefinitely until it fails. I am attaching the terminal output below for reference. 

Do you know why this issue is happening? What is the recommended way to go about this?

Thanks,
Walid

```
...
#
# To deactivate an active environment, use
#
#     $ conda deactivate


checking python dependencies
Solving environment: failed

CondaError: KeyboardInterrupt

Terminated

(base) [wabuala@noderome102 IRIS]$ (base) [wabuala@splprhpc07 ~]$
```

**Comment by EricKutschera** [comment]
I was able to run `./install all` this morning and it succeeded. It took about 15 minutes to solve the environment

This is the line of the install script that would have been running: https://github.com/Xinglab/IRIS/blob/v2.0.1/install#L83

You can try running that command with `mamba` which usually gives a decent error message when an environment can't be solved: (https://mamba.readthedocs.io/en/latest/installation.html)

```
conda activate ./conda_env_2
mamba install -c conda-forge -c bioconda --file conda_requirements_py2.txt --file conda_requirements_py2_optional.txt
```

Maybe there is something in your conda config that prevents the environment from being solved. Can you post the output of `conda config --show-sources`

**Comment by walidabualafia** [comment]
Hi Eric,

Apologies for the delayed response. I managed to get `./install all` working on our cluster. I have all the dependencies currently installed, and all 3 environments were built.

However, I have a question. The only remaining step is the configuration for SnakeMake so that IRIS can submit jobs to the cluster. Our cluster is running an implementation of the LSF Scheduler. The provided SnakeMake profile that comes with IRIS is configured for Slurm. Do you have/provide configurations for other job schedulers, or would I have to manually adapt the `.py` files to LSF?

Cheers!

**Comment by EricKutschera** [comment]
You'll need to edit this file: https://github.com/Xinglab/IRIS/blob/master/snakemake_profile/cluster_commands.py

The default implementation is for slurm. There is also `cluster_commands_sge.py` which I used before when our cluster used SGE. The function `submit_command` returns a command line to submit the job to the cluster. That command should print a job ID and the function `try_extract_job_id_from_submit_output` parses the job ID from the output. Then the job ID is used to check the job status with the command returned by `status_command`. The function `try_extract_job_info_from_status_output` is a bit complicated in the slurm implementation. It's trying to get a lot of extra information about job resource usage, but all that is really needed is the `status` which is one of `running`, `success`, or `failed`. I haven't used LSF, but hopefully it is easy to create submit and status commands, and parse the job ID and the job status from the output

**Comment by walidabualafia** [comment]
There seems to be a lot of indentation mismatches in bin/IRIS. Can you confirm?

**Comment by walidabualafia** [comment]
I fixed them, and got the bin running. I am getting the error message below. Is there a recommended way to install IRIS as a python module in the conda env? I am currently running `conda_env_3`.

Traceback (most recent call last):
  File "/research/rgs01/applications/hpcf/authorized_apps/rhel7_apps/iris/vendor/IRIS/bin/IRIS", line 9, in <module>
    from IRIS import config
ModuleNotFoundError: No module named 'IRIS'

**Comment by EricKutschera** [comment]
IRIS is written for Python 2

There are a mix of tabs and spaces in https://github.com/Xinglab/IRIS/blob/master/bin/IRIS, but that doesn't cause an error in Python 2

The install script installs IRIS to conda_env_2 here: https://github.com/Xinglab/IRIS/blob/v2.0.1/install#L145

**Comment by walidabualafia** [comment]
Eric,

Thanks for all your help so far. I got IRIS running, and I adapted the SnakeMake Profile to LSF. However, I am currently running into a confusing issue. For each scheduled job, I am getting:
```
error: expected output to look like "Job <...>"
Job <196618620> is submitted to default queue <standard>.

Error submitting jobscript (exit code 1):
```
The jobs are being submitted to the queue, but for some reason they cannot load the jobscripts. I checked the job scripts, and it seems like bash, so it should run on LSF without hiccups. The error `Error submitting jobscript (exit code 1):` is a Slurm specific error. Have you seen this before?

Towards the end of execution, I get this:
```
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
workflow error
Complete log: .snakemake/log/2023-07-11T154233.004445.snakemake.log
```


I am attaching the log file below for your reference.
[2023-07-11T154233.004445.snakemake.log](https://github.com/Xinglab/IRIS/files/12021459/2023-07-11T154233.004445.snakemake.log)

**Comment by EricKutschera** [comment]
I think this is the line that prints the main error: https://github.com/Xinglab/IRIS/blob/v2.0.1/snakemake_profile/cluster_submit.py#L121

The error would be from `try_extract_job_id_from_submit_output` in `cluster_commands.py`. This is the slurm implementation https://github.com/Xinglab/IRIS/blob/v2.0.1/snakemake_profile/cluster_commands.py#L41 but I think you wrote new code for your scheduler. From `Job <196618620> is submitted to default queue <standard>.` it looks like the job was submitted successfully, but the code wasn't able to get the job ID

**Comment by walidabualafia** [comment]
I found something! I printed the path of job script, as I assumed LSF is unable to find the job script in the path.

The path of the jobscript that it is trying to run is `MY JOB SCRIPT IS ====> /research/rgs01/applications/hpcf/authorized_apps/rhel7_apps/iris/vendor/IRIS/.snakemake/tmp.ooethj5_/snakejob.download_reference_file.6.sh`

However, when I `ls .snakemake`, the directory `.snakemake/tmp.ooethj5_` does not exist. The job script with the name `snakejob.download_reference_file.6.sh` lives in `./snakemake/tmp.ydeg2cft`.

Any recommendations?

**Comment by walidabualafia** [comment]
> I think this is the line that prints the main error: https://github.com/Xinglab/IRIS/blob/v2.0.1/snakemake_profile/cluster_submit.py#L121
> 
> The error would be from `try_extract_job_id_from_submit_output` in `cluster_commands.py`. This is the slurm implementation https://github.com/Xinglab/IRIS/blob/v2.0.1/snakemake_profile/cluster_commands.py#L41 but I think you wrote new code for your scheduler. From `Job <196618620> is submitted to default queue <standard>.` it looks like the job was submitted successfully, but the code wasn't able to get the job ID

This was the solution! Thank you, Eric! I was not stripping the job id correctly. Pipeline works like a charm! :)
